# Generated by Django 4.1.5 on 2023-09-30 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="E_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="E_Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Composition",
                "verbose_name_plural": "Compositions",
            },
        ),
        migrations.CreateModel(
            name="E_Commerce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=65, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("slug", models.SlugField(unique=True)),
                ("price", models.FloatField(default=1, verbose_name="Price")),
                ("quantity", models.IntegerField(default=0, verbose_name="Quantity")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update at"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=False, verbose_name="Is Available"),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="covers/%Y/%m/%d/", verbose_name="Cover/Image"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.e_category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "composition",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.e_composition",
                        verbose_name="Compositions",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="tags.tag", verbose_name="TAG"
                    ),
                ),
            ],
            options={"verbose_name": "Object", "verbose_name_plural": "Objects",},
        ),
        migrations.CreateModel(
            name="E_Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtde", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "e_commerce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.e_commerce",
                    ),
                ),
            ],
            options={"verbose_name": "Cart", "verbose_name_plural": "Requests",},
        ),
        migrations.CreateModel(
            name="Covers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="covers/%Y/%m/%d/", verbose_name="Cover/Image"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.e_commerce",
                    ),
                ),
            ],
        ),
    ]
