# Generated by Django 4.1.5 on 2023-10-02 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="e_cart",
            name="e_commerce",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.e_commerce",
            ),
        ),
        migrations.AlterField(
            model_name="e_commerce",
            name="cover",
            field=models.TextField(blank=True, null=True),
        ),
    ]
