# Generated by Django 4.1.5 on 2023-10-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_e_category_name_alter_e_commerce_title_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Covers",),
    ]
