# Generated by Django 4.1.5 on 2023-10-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_delete_covers"),
    ]

    operations = [
        migrations.RemoveField(model_name="e_commerce", name="cover",),
        migrations.CreateModel(
            name="Covers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_img", models.CharField(max_length=60)),
                (
                    "cover",
                    models.ImageField(
                        upload_to="covers/%Y/%m/%d/", verbose_name="Cover/Image"
                    ),
                ),
                (
                    "e_commerce_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.e_commerce",
                    ),
                ),
            ],
            options={"verbose_name": "Cover", "verbose_name_plural": "Images",},
        ),
    ]
