# Generated by Django 4.1.5 on 2023-09-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="cart", field=models.TextField(blank=True),
        ),
    ]
